import re

ROWS = [
    ("new", "New"),
    ("used", "Used"),
    ("total", "Total"),
    ("rating", "Google rating"),
    ("reviews", "Google reviews"),
    ("place_id", "Google place ID"),
    ("hours", "Hours"),
    ("phone", "Phone"),
    ("address", "Address"),
]


def render_snapshot(bundle_dir, data, as_of):
    title = bundle_dir.replace("-", " ").title()
    lines = [
        "---",
        "type: Data Snapshot",
        f'title: "{title} - Data Snapshot"',
        f'description: "Machine-managed PromptGraph data snapshot for {bundle_dir}, as of {as_of}."',
        "tags:",
        "  - data-snapshot",
        "  - promptgraph",
        f"timestamp: {as_of}",
        "---",
        "",
        f"# {title} - Data Snapshot",
        "",
        f"Machine-managed snapshot generated by the OKF refresh pipeline. As of {as_of}.",
        "",
        "| Field | Value |",
        "|---|---|",
    ]
    for key, label in ROWS:
        lines.append(f"| {label} | {data.get(key, 'unknown')} |")
    lines.append("")
    return "\n".join(lines)


def parse_snapshot(md):
    out = {}
    label_to_key = {label: key for key, label in ROWS}
    for line in md.splitlines():
        m = re.match(r"^\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*$", line)
        if not m:
            continue
        label, value = m.group(1), m.group(2)
        if label in label_to_key and label != "Field":
            out[label_to_key[label]] = value
    return out


def diff_existing(old_md, new_md):
    if old_md is None:
        return True
    return old_md != new_md
